export const countrySummary = [
  {
    countryName: "Guyana",
    geographicRegion: ["South America", "Caribbean"],
    startYear: "1838",
    endYear: "1917",
    origins: ["Bhojpur", "Awadh"],
    numVoyages: 534,
    numIndentures: 239000,
    shipDataAvailable: false,
    color: "#e76f51",
  },
  {
    countryName: "Trinidad & Tobago",
    geographicRegion: ["Caribbean"],
    startYear: "1845",
    endYear: "1917",
    origins: ["Bhojpur", "Awadh"],
    numVoyages: 328,
    numIndentures: 144000,
    shipDataAvailable: true,
    shipDataSource: {
      text: "Trinidad & Tobago National Archives",
      link: 'https://www.natt.gov.tt/sites/default/files/images/General-Registers-of-Indian-Indentured-Labourers.pdf'
    },
    color: "#f4a261",
  },
  {
    countryName: "Jamaica",
    geographicRegion: ["Caribbean"],
    startYear: "1845",
    endYear: "1907",
    origins: ["Bhojpur", "Awadh"],
    numVoyages: 10,
    numIndentures: 36000,
    shipDataAvailable: false,
    color: "#e9c46a",
  },
  {
    countryName: "Suriname",
    geographicRegion: ["South America", "Caribbean"],
    startYear: "1873",
    endYear: "1916",
    origins: ["Bhojpur", "Awadh"],
    numVoyages: 64,
    numIndentures: 34000,
    shipDataAvailable: true,
    shipDataSource: {
      text: "National Archives Suriname",
      link: 'https://nationaalarchief.sr/zoekhulpen/hindoestaanse-contractarbeiders-in-suriname-1873-1916'
    },
    color: "#8ab17d",
  },
  {
    countryName: "South Africa",
    geographicRegion: ["Africa"],
    startYear: "1860",
    endYear: "1911",
    origins: ["Uttar Pradesh", "Bihar"],
    numVoyages: 384,
    numIndentures: 152000,
    shipDataAvailable: false,
    color: "#2a9d8f",
  },
  {
    countryName: "Mauritius",
    geographicRegion: ["Indian Ocean"],
    startYear: "1834",
    endYear: "1912",
    origins: ["Uttar Pradesh", "Bihar"],
    numVoyages: 453,
    numIndentures: 450000,
    shipDataAvailable: false,
    color: "#287271",
  },
  {
    countryName: "Fiji",
    geographicRegion: ["Oceania"],
    startYear: "1879",
    endYear: "1916",
    origins: ["Uttar Pradesh", "Bihar"],
    numVoyages: 87,
    numIndentures: 60500,
    shipDataAvailable: true,
    shipDataSource: {
      text: "National Library of Australia",
      link: 'https://www.nla.gov.au/research-guides/indian-emigration-passes-to-fiji-1879-1919/access-by-ships-name'
    },
    color: "#923e4d",
  },
];
