export const countrySummary = [
  {
    countryName: "Guyana",
    geographicRegion: ["South America", "Caribbean"],
    startYear: "1838",
    endYear: "1917",
    origins: ["Uttar Pradesh", "Bihar"],
    numVoyages: 534,
    numIndentures: 239000,
    route: "indiaToGuyana",
    shipDataAvailable: false,
  },
  {
    countryName: "Trinidad & Tobago",
    geographicRegion: ["Caribbean"],
    startYear: "1840",
    endYear: "1907",
    origins: ["Uttar Pradesh", "Bihar"],
    numVoyages: 328,
    numIndentures: 144000,
    route: "indiaToTrinidad",
    shipDataAvailable: true,
  },
  {
    countryName: "Jamaica",
    geographicRegion: ["Caribbean"],
    startYear: "1840",
    endYear: "1907",
    origins: ["Uttar Pradesh", "Bihar"],
    numVoyages: 10,
    numIndentures: 36000,
    route: "indiaToJamaica",
    shipDataAvailable: false,
  },
  {
    countryName: "Suriname",
    geographicRegion: ["South America", "Caribbean"],
    startYear: "1840",
    endYear: "1907",
    origins: ["Uttar Pradesh", "Bihar"],
    numVoyages: 10,
    numIndentures: 34000,
    route: "indiaToSuriname",
    shipDataAvailable: true,
  },
  {
    countryName: "South Africa",
    geographicRegion: ["Africa"],
    startYear: "1840",
    endYear: "1907",
    origins: ["Uttar Pradesh", "Bihar"],
    numVoyages: 384,
    numIndentures: 152000,
    route: "indiaToSouthAfrica",
    shipDataAvailable: false,
  },
  {
    countryName: "Mauritius",
    geographicRegion: ["Mascarene Islands", "Indian Ocean"],
    startYear: "1840",
    endYear: "1907",
    origins: ["Uttar Pradesh", "Bihar"],
    numVoyages: 10,
    numIndentures: 10,
    route: "indiaToMauritius",
    shipDataAvailable: false,
  },
  {
    countryName: "Fiji",
    geographicRegion: ["Oceania", "Pacific Ocean"],
    startYear: "1879",
    endYear: "1916",
    origins: ["Uttar Pradesh", "Bihar"],
    numVoyages: 114,
    numIndentures: 60513,
    route: "indiaToFiji",
    shipDataAvailable: true,
  },
];
